server:
  port: 8889
  servlet:
    context-path: "/test/"
spring:
  application:
    name: moudel1
  #  redis:
  #    host:
  #    port: 6379
  #    database: 0
  #    password:
  #    timeout:
  #    jedis:
  #      pool:
  #        max-wait: -1
  #        max-idle: 8
  #        min-idle: 0
  #        max-active:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://ip??:??;DatabaseName=????

    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #    url: jdbc:oracle:thin:@localhost:1521:orcl

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.204.126:3306/text?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: test
    password: xiaozhupeiqi
    hikari:
      #????????
      allow-pool-suspension: true
      minimum-idle: 5
      #?????????? ??600000?10???
      idle-timeout: 600000
#      ????????????10
      maximum-pool-size: 10
      #      ????????????????,????true
      auto-commit: true
      pool-name: MyHikariCP
#      ??????????????????0???????????1800000?30??
      max-lifetime: 1800000
      #???????? ??ms ??3000
      connection-timeout: 3000
#      ????????????250ms?????connectionTimeout????500
      validation-timeout: 5000

  servlet:
    multipart:
#      ??????  ??1MB
      max-file-size: 10MB
#     ????????????  ??10MB
      max-request-size: 10MB
#      ???????????????? true
      enabled: true
#      ?????????????
#      location:E:\\temp
#      ??????????????? false
#      resolve-lazily: false
#  ??????????????? 0
#      file-size-threshold:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    ??
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #  ?????????????camel case????????????? A_COLUMN??????? ??? Java ??? aColumn?????? ??????
    map-underscore-to-camel-case: true
    #MyBatis ?????????????????????????? MyBatis ????????????????????????
#    WARNING???????????????  FAILING????????????????????
    auto-mapping-unknown-column-behavior: none
#   SESSION?session????????session???????????????  STATEMENT???????
    local-cache-scope: session
  #  myBatis ??????????????? MyBatis ??????????????????????
  #  NONE???????? #  PARTIAL??????? resultMap ?????? #  FULL????? resultMap ???????
  #  auto-mapping-behavior: partial
  #  jdbc-type-for-null: 'null'
  type-aliases-package: com.moudel1
  mapper-locations: classpath:dao/*.xml
  #??????? MyBatis XML ????????????
#  check-config-location: true
  scripting-language-driver:
    thymeleaf:
      template-file:
#        fe80::40c9:460a:84ea:3850%7
#        ?? utf-8
        encoding: utf-8











